# render.yaml - Fixed Database Type

services:
  - type: web
    name: reach-app # Your application name on Render
    env: python
    region: oregon # Choose a region closest to your users (e.g., oregon, frankfurt, singapore)
    plan: free # Use the free tier for now
    branch: main # The branch to deploy from
    rootDir: . # Assuming your Django project root is the repository root

    # Build Command: Installs dependencies and collects static files
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    # Start Command: Runs Gunicorn to serve your Django app
    # Replace 'reach_app.wsgi' with your actual project_name.wsgi module path
    startCommand: gunicorn reach_app.wsgi:application

    # Environment Variables
    envVars:
      - key: DATABASE_URL # Render automatically provides this for its PostgreSQL database
        fromDatabase:
          name: reach-db # Refers to the database service defined below
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render will generate a strong secret key for you
      - key: WEB_CONCURRENCY
        value: 4 # Recommended for Gunicorn
      - key: PYTHON_VERSION
        value: 3.13.5 # Match your local Python version
      - key: DISABLE_COLLECTSTATIC # Important to prevent collectstatic on every subsequent deploy
        value: 1
      - key: DEBUG
        value: "False" # Ensure debug is false in production
      - key: PYTHONUNBUFFERED # Important for real-time log streaming
        value: "1"

    # Health Check (optional but recommended)
    healthCheckPath: /admin/login/ # A simple URL to check if the app is running

  - type: database # FIXED: Changed from 'postgres' to 'database'
    name: reach-db
    region: oregon # Must be the same region as your web service
    plan: free # Free tier for database
    databaseName: reach_db # Name for your database
    user: reach_user # User for your database